
const IntoMe = {
  titleName: 'นาย',
  fName: 'วัชระชัย',
  lName: 'สำคัญ',
  nName: 'เอิร์ธ',
  birthday: 'เกิดวันที่ 17 กรกฎาคม 2543',
  interested: 'Full-Stack Developer และ Mobile Developer ตามลําดับสามารถใช้งานภาษา JavaScript, TypeScript และกําลังศึกษาเพิ่มเติมอย่างต่อเนื่อง',
  js: 'JavaScript, TypeScript (ระดับดี)',
  basic: 'C, C++, Go, PHP, JAVA, SQL  (พื้นฐาน)',
  feReact: 'React, React Native (redux toolkit)',
  feVue: 'Vue, NuxtJS (vuex)',
  beNode: 'NodeJS, Nest, Express',
  beSocket: 'Socket.io, Sse (พื้นฐาน)',
  beDocker: 'docker-compose (พื้นฐาน)',
  db: 'PostgresSQL, MySQL',
  tVs: 'Visual Studio Code',
  tDocker: 'Docker',
  tAS: 'Android Studio',
  tGit: 'Github Desktop, SourceTree',
  tPost: 'Postman',
  tDB: 'DBeaver',
  add: 'ต.หนองหิน อ.หนองหิน จ.เลย',
  addP: 'ปัจจุบันอาศัยอยู่ที่ ขอนแก่น',
  email: 'watcharachai.sk@gmail.com',
  tol: '0864552623',
  git: 'https://github.com/WatcharachaiSk',
  titleTimeOne: 'มิ.ย. - ต.ค. 2565 (4 เดือน)',
  titleTimeOneTitle: 'สหกิจศึกษา',
  titleTimeOneComp: 'อิเลคทรอนิกส์ เชลล์ จำกัด Eectronic Shell Co.,Ltd.',
  titleTimeOneRank: 'Mobile Developer (React Native, TypeScript)',
  titleTimeOneProj: 'พัฒนาระบบตรวจสอบครุภัณฑ์โดยการใช้กล้องมือถือ',
  titleTimeTwo: 'พ.ย. 2565 - ก.พ. 2566 (4 เดือน)',
  titleTimeTwoComp: 'ปริญญานิพนธ์',
  titleTimeTwoRank: 'Full-Stack (React, NodeJS Express)',
  titleTimeTwoProj: 'การพัฒนาระบบจัดครุภัณฑ์ผ่านเว็บไซต์และระบบปฏิบัติการแอนดรอยด์',
  titleTimeTree: 'เม.ย. 2566 - ปัจจุบัน',
  titleTimeTreeTitle: 'Junior Developer',
  titleTimeTreeRank: 'Full-Stack (Vue, React, NestJS)',
  titleTimeTreeComp: 'อิเลคทรอนิกส์ เชลล์ จำกัด Eectronic Shell Co.,Ltd.',
  delTimeTreeComp: 'ออกแบบและพัฒนาระบบตรวจสอบครุภัณฑ์โดยมีการใช้กล้องมือถือเพื่อสแกนคิวอาร์โค้ดและเชื่อมต่อกับ API ของบริษัท - พัฒนาด้วย React Native, TypeScript',
  
  titleEducOneTh: 'เทคนิคคอมพิวเตอร์',
  titleEducOneEn: 'ComputerTechnology',
  titleEducOneGPA: '3.29GPA',
  subEducOneTh: 'วิทยาลัยเทคนิคเลย',
  subEducOneEn: 'LoeiTechnicalCollege',
  rankEducOne: 'ประกาศนียบัตรวิชาชีพ',
  yearEducOne: '2559 - 2561',

  titleEducTwoTh: 'วิศวกรรมคอมพิวเตอร์',
  titleEducTwoEn: 'ComputerEngineering',
  titleEducTwoGPA: '3.10GPA',
  subEducTwoTh: 'มหาวิทยาลัยเทคโนโลยีราชมงคลอีสานวิทยาเขตขอนแก่น',
  subEducTwoEn: 'Rajamangala University of Technology Isan Khonkaen Campus',
  rankEducTwo: 'ปริญญาตรี',
  yearEducTwo: '2562 – 2565'

};

export default IntoMe

